name: Generate Snake Contribution Grid

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every midnight
  workflow_dispatch:   # Allows manual trigger

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Jackhammer9
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create Output Branch
        run: |
          git fetch origin
          git branch output || true
          git checkout output || git checkout -b output
          git pull origin output || true

      - name: Push the Generated Snake
        run: |
          mkdir -p dist
          git add -f dist/github-contribution-grid-snake.svg
          git commit -m "Update GitHub contribution snake animation"
          git push origin output --force
