name: Generate Snake Contribution Grid

on:
  schedule:
    - cron: "0 0 * * *"  # Runs once a day
  workflow_dispatch:   # Allows manual trigger

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Jackhammer9
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Upload Generated Snake
        uses: actions/upload-artifact@v3
        with:
          name: contribution-grid-snake
          path: dist/github-contribution-grid-snake.svg
